name: charts-helm-checks

on:
  pull_request:

env:
  HELM_VERSION: v3.16.4

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changes-charts: ${{ steps.filter.outputs.charts }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            charts:
              - '.github/workflows/charts-helm-checks.yml'
              - 'charts/**'

  lint-and-test:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.charts-charts == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: helm/chart-testing-action@v2

      - run: |
          ct lint --config .github/config/ct.yaml
          ct list-changed --config .github/config/ct.yaml
